### ISSUE TITLE
Use info from http://datahub.io/dataset/uk-public-bodies

### ISSUE THREAD

**Issue by rufuspollock** [okfn/publicbodies#24]
Use info from http://datahub.io/dataset/uk-public-bodies

**Comment by augusto-herrmann** [comment]
It seems this dataset in Data Hub hasn't been updated since 2013.

![Screenshot 2021-06-14 at 10-59-14 UK Public Bodies - the Datahub](https://user-images.githubusercontent.com/1058414/121905958-0657a280-cd01-11eb-88a3-7f00d4ac1d68.png)

And the url from reference.data.gov.uk gives a 404 not found error now.

Considering this issue has been stale for years, I'm closing it now. We can open another one once we find an updated data source for uk data.
