### ISSUE TITLE
Adding publicbodies as IATI codelist

### ISSUE THREAD

**Issue by danfowler** [okfn/publicbodies#74]
As suggested by @timgdavies [here](https://github.com/openspending/fiscal-data-package/issues/13), we should submit a code for PublicBodies.org to IATI's [Organisation Registration Agency codelist](http://iatistandard.org/202/codelists/OrganisationRegistrationAgency/).

Related: https://github.com/okfn/publicbodies/issues/41

Something like this?

| Code | Name | Description | Category | URL | Public Database? |
| --- | --- | --- | --- | --- | --- |
| XI-PB | Public Bodies | Public Bodies aims to provide a unique ID for every part of every government. | XI | http://publicbodies.org/ | Yes |

How to do it:

> If a Registation Agency that you wish to use is not on this list, please contact support@iatistandard.org

**Comment by danfowler** [comment]
@rgrp thoughts?

**Comment by timgdavies** [comment]
+1

**Comment by bill-anderson** [comment]
Will forward this to IATI Tech Team. Takes 2 weeks to process (I think)

**Comment by rory09** [comment]
Hello all,

This looks great! I've just added it to our non-embedded codelist consultations - see [here](http://support.iatistandard.org/entries/107809263-Add-Organisation-Registration-Agency-for-publicbodies-org). 

I'm just thinking - when constructing an [IATI Ogranisation Identifier](http://iatistandard.org/202/organisation-identifiers/), the regex `[^\/\&\|\?]+` has to be satisfied. This was partly done so that IATI identifiers would play nice with URIs/URLs.

One simple fix would be for publishers to use a dash or underscore instead of a slash to concatenate the country code to the id.

So where an [entry on Public Bodies](https://github.com/okfn/publicbodies/blob/master/data/gb.csv#L2) reads:

|            id             |          name          | abbreviation | other_names | description | ... |
|---------------------------|------------------------|--------------|-------------|-------------|-----|
| gb/2010-rotherham-limited | 2010 Rotherham Limited | ...          | ...         | ...         | ... |

The IATI Identifier for the corresponding organisation could be `XI-PB-GB-2010-rotherham-limited` or `XI-PB-GB_2010-rotherham-limited`. 

The only issue with this is that will hinder lookup/searching from Public Bodies to IATI or vice versa, and secondary reporters would have to find out or decide how to convert between the two. Does anyone have any proposals of how best to deal with this? 

I imagine it would be quite a big ask for you the replace the slash with an underscore, or something similar, but for anyone wanting to use an ID from this database in a URL it would certainly be helpful.

Just a thought. I look forward to seeing this develop - I expect it to be very helpful for data users in IATI or otherwise.

Thanks!

**Comment by rgrp** [comment]
@rory09 how does IATI (or specs that IATI references) generally handle "country code + in country identifier" stuff? The reason for the `gb/` was actually so that it worked in urls in that you had the country then the within country identifier?

**Comment by rory09** [comment]
Hi @rgrp - that's interesting. The central difference with IATI is that we use identifiers as string references within XML attributes. So, for instance, if a publisher were to declare a [participating organisation](http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/participating-org/) within an IATI activity, they would want to include the following line of XML:

``` xml
  <participating-org ref="GB-COH-123456789" role="1" type="40"> 
  <!-- the role and type values are declared in codelists online, along 
       with the codes for country and registration agency -->
	<narrative>Name of Agency</narrative>
  </participating-org>
```

here, the `ref="..."` is where the identifier is declared. The above follows the structure `"<country code>-<agency code>-<agency assigned identifier>"`, in this case Great Britain, Companies House, and digits 1-9.

So the short answer is that IATI handles this kind of concatenation with dashes.

**Comment by timgdavies** [comment]
Public bodies is in the http://org-id.guide codelist that will shortly replace the IATI list (http://org-id.guide/list/XI-PB) 

I don't think the '/' character substitution issue has been resolved yet.

**Comment by todrobbins** [comment]
Thanks for the update @timgdavies.

**Comment by VladimirAlexiev** [comment]
@timgdavies are you speaking on behalf of IATI? 

@todrobbins XI-PB is included in http://iatistandard.org/202/codelists/OrganisationRegistrationAgency/, so you can close this issue

The "slash vs underscore" issue reflects a big difference in philosophy, so I believe it merits a new issue to be opened: https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/152

"Does this mean when an official register becomes available, we should deprecate "aggregator" identifier schemes or URLs (like OpenCorporates or PublicBodies) in favor of that official register?" (please comment there)

**Comment by timgdavies** [comment]
@VladimirAlexiev I don't speak for IATI - but the issue where this change is proposed and so far has had no objections can be found at https://discuss.iatistandard.org/t/migration-of-organisationregistrationagency-codelist-to-org-id-guide/851

**Comment by VladimirAlexiev** [comment]
Thanks for the info!

**Comment by rory09** [comment]
Apologies all, this is my personal email and I think these emails have been
falling foul of an overzealous filter I set up to deal with github
notifications.

Thank you Tim for clearing this up. I should mention that whilst I used to
be a part of the IATI secretariat, I'm no a member of Open Data Services
Co-operative along with Tim, so I also don't speak for IATI. That being
said, I've worked with Tim in collaboration with the IATI Secretariat on
the org-id.guide project, and I would agree that it is very likely to
become the official organisation-id prefix list.

Thanks for setting up the new ticket, Vladimir - I'll see you in the
comments section there!

Best,
Rory

**Comment by augusto-herrmann** [comment]
> @todrobbins XI-PB is included in http://iatistandard.org/202/codelists/OrganisationRegistrationAgency/, so you can close this issue

Indeed it included there. @VladimirAlexiev thank you for pointing it out.

However, the line has some information that I think is incorrect. In particular the `Category` and `Public Database?` fields:


Code | Name | Description | Category | URL | Public Database?
-- | -- | -- | -- | -- | --
XI-PB | Public Bodies - Open Knowledge Foundation | Public Bodies is an Open Knowledge Foundation (OKF) project that  aims to provide a unique ID for every part of every government. The main  website is a portal for linking to profile pages for countries whose  public bodies OKF has recorded. There are also links to directly  download CSVs of this information. Data available on the following  countries/regions - Brazil, European Union, Germany, Greece, New  Zealand, Switzerland, United Kingdom, United States | BR | http://publicbodies.org/ | False

Do you know how this could be fixed?

**Comment by augusto-herrmann** [comment]
Considering that the IATI codelist is no longer maintained (as highlighted by @PetyaKangalova above), and that we are already present at its successor list ([org-id.guide](http://org-id.guide/list/XI-PB)), if no one has any objections (esp. @danfowler, @timgdavies & @rufuspollock who were involved when opening it), I'll soon close this issue as solved.
